### ISSUE TITLE
New input about the socket problem

### ISSUE THREAD

**Issue by AndersMalmgren** [shtejv/ARDrone-Control-.NET#34]
After increase of timeout I do not receive socket timeoutes anymore, but sometimes I get this error, and it only sometimes, sometimes I can fly 100s of meters away from drone without problems..

The error is always on port 5556 (Command port)

System.Net.Sockets.SocketException (0x80004005): The requested address is not valid in its context
   at System.Net.Sockets.Socket.SendTo(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint remoteEP)
   at System.Net.Sockets.UdpClient.Send(Byte[] dgram, Int32 bytes, IPEndPoint endPoint)
   at ARDrone.Control.Network.UdpWorker.SendMessage(Byte[] message) in C:\Users\ama\Documents\Projekt\Anders.ARDrone\ARDroneControlLibrary\Network\UdpWorker.cs:line 75
2011-09-04 16:00:44,768 [ARDrone.Control.Workers.CommandSender_WorkerThread] ERROR ProcessThreadedException
System.Net.Sockets.SocketException (0x80004005): The requested address is not valid in its context
   at System.Net.Sockets.Socket.SendTo(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint remoteEP)
   at System.Net.Sockets.UdpClient.Send(Byte[] dgram, Int32 bytes, IPEndPoint endPoint)
   at ARDrone.Control.Network.UdpWorker.SendMessage(Byte[] message) in C:\Users\ama\Documents\Projekt\Anders.ARDrone\ARDroneControlLibrary\Network\UdpWorker.cs:line 80
   at ARDrone.Control.Network.UdpWorker.SendMessage(String message) in C:\Users\ama\Documents\Projekt\Anders.ARDrone\ARDroneControlLibrary\Network\UdpWorker.cs:line 68
   at ARDrone.Control.Workers.CommandSender.ProcessWorkerThread() in C:\Users\ama\Documents\Projekt\Anders.ARDrone\ARDroneControlLibrary\Workers\CommandSender.cs:line 76
   at ARDrone.Control.Network.NetworkWorker.ProcessWorkerThreadInternally() in C:\Users\ama\Documents\Projekt\Anders.ARDrone\ARDroneControlLibrary\Network\NetworkWorker.cs:line 104

**Comment by shtejv** [comment]
Thanks a lot. I'll use that information to try to recreate the problem.
